
name: augmented-maskrcnn
#prefix: /your/custom/path/envs/augmented-maskrcnn
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.6
  - pip=19.3.1
  - anaconda::cython
  - pytorch::pytorch>=1.6.0
  - pytorch::torchvision>=0.7.0
  - conda-forge::imgaug=0.4.0
  - pip:
    - git+https://github.com/gautamchitnis/cocoapi.git@cocodataset-master#subdirectory=PythonAPI
    - numpy<=1.17.4
    - scikit-image==0.16.2
    - jsonschema>=2.6.0
    - albumentations==0.4.6
    - tensorboard==2.0.0
    - torch-optimizer==0.0.1a15
