
name: augmented-maskrcnn
#prefix: /your/custom/path/envs/augmented-maskrcnn
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.6
  - pip
  - anaconda::cython
  - pytorch::pytorch>=1.4.0
  - pytorch::torchvision>=0.5.0
  - anaconda::jsonschema>=2.6.0
  - albumentations::albumentations=0.4.5
  - conda-forge::imgaug=0.2.9
  - pip:
    - matplotlib==3.2.0
    - numpy<=1.17.4
    - scikit-image==0.16.2
    - git+https://github.com/gautamchitnis/cocoapi.git#subdirectory=PythonAPI
