
name: augmented-maskrcnn
#prefix: /your/custom/path/envs/augmented-maskrcnn
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.6
  - pip=19.3.1
  - pytorch::pytorch>=1.5.0
  - pytorch::torchvision>=0.6.0
  - anaconda::jsonschema>=2.6.0
  - albumentations::albumentations=0.4.5
  - conda-forge::imgaug=0.4.0
  - pip:
    - numpy<=1.17.4
    - scikit-image==0.16.2
    - pycocotools-fix==2.0.0.1
    - jsonschema>=2.6.0
