# Random seed to reproduce the results
SEED: 999
# Directory to dataset root
DATA_ROOT: ""
# Path to annotation file (should be in coco object detection format)
COCO_PATH: ""
# Training model checkpoints and losses will be saved in the folder experiments/EXPERIMENT_NAME/
EXPERIMENT_NAME: "exp1"
# Path to the model to be used during predict
MODEL_PATH: "experiments/exp1/maskrcnn-best.pt"

# Optimizer name ("sgd", "adam", "adabound", "lamb" or "radam")
OPTIMIZER_NAME: "sgd"
# For more info on the optimizer params:
# https://pytorch.org/docs/stable/optim.html
# https://pytorch-optimizer.readthedocs.io/en/latest/?badge=latest
OPTIMIZER_WEIGHT_DECAY: 0.0005
OPTIMIZER_MOMENTUM: 0.9
OPTIMIZER_BETAS: [0.9, 0.999]
OPTIMIZER_EPS: 0.00000001
OPTIMIZER_AMSGRAD: False
OPTIMIZER_ADABOUND_GAMMA: 0.001
OPTIMIZER_ADABOUND_FINAL_LR: 0.1
# Optimizer learning rate
LEARNING_RATE: 0.0001
# Optimizer learning rate schedule parameters
LEARNING_RATE_STEP_SIZE: 3
LEARNING_RATE_GAMMA: 0.1

# Number of trainable (not frozen) resnet layers starting from final block (btw 0-5)
TRAINABLE_BACKBONE_LAYERS: 3
# Will be used while generating anchors for a set of feature maps and image sizes
RPN_ANCHOR_SIZES: [32, 64, 128, 256, 512]
RPN_ANCHOR_ASPECT_RATIOS: [0.5, 1.0, 2.0]

# Number of iterations to print/log
LOG_FREQ: 40
# Train split rate of the dataset
TRAIN_SPLIT_RATE: 0.8
# Batch size:
BATCH_SIZE: 1
# Total epoch number
NUM_EPOCH: 10
# Device to perform train/inference (cuda:0, cpu etc.)
DEVICE: "cuda:0"
# Thread number to be used for dataloading
NUM_WORKERS: 0

