# Random seed to reproduce the results
SEED: 999
# Path to dataset root
DATA_ROOT: "/home/fatih/Downloads/gag_data/y3_gag_trainSet/train/input"
# Path to annotation file (should be in coco object detection format)
COCO_PATH: "/home/fatih/Downloads/gag_data/y3_gag_trainSet/train/gag_train_coco.json"
# Training model checkpoints and losses will be saved in the folder experiments/EXPERIMENT_NAME/
EXPERIMENT_NAME: "exp1"
# Number of trainable (not frozen) resnet layers starting from final block (btw 0-5)
TRAINABLE_BACKBONE_LAYERS: 3
# Path to the model to be used during predict
MODEL_PATH: "experiments/exp1/maskrcnn-best.pt"
# Optimizer ("adam" or "sgd")
OPTIMIZER: "sgd"
# Optimizer learning rate
LEARNING_RATE: 0.0001
# Number of iterations to print/log
LOG_FREQ: 40
# Batch size
BATCH_SIZE: 1
# Total epoch number
NUM_EPOCH: 10
# Device to perform train/inference (cuda:0, cpu etc.)
DEVICE: "cuda:0"

